name: Create draft release

on:
  workflow_dispatch:
    inputs:
      forced_commit_id:
        description: 'Force using artifacts from specific commit? If provided, this will try and use the artifacts from the given commit, regardless of build status'
        required: false

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      AZURE_DEVOPS_TOKEN: "${{ secrets.AZURE_DEVOPS_TOKEN }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.101'

      - name: "Configure Git Credentials"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Ensure dd-lib-dotnet-init images are published
        shell: bash
        run: |
          if ! docker manifest inspect ghcr.io/datadog/dd-trace-dotnet/dd-lib-dotnet-init:${{ github.sha }} ; then
            echo "::error::dd-lib-dotnet-init image not present : ${{ github.sha }}"
            exit 1
          fi

          if ! docker manifest inspect ghcr.io/datadog/dd-trace-dotnet/dd-lib-dotnet-init:${{ github.sha }}-musl ; then
            echo "::error::dd-lib-dotnet-init image not present : ${{ github.sha }}-musl"
            exit 1
          fi

      - name: "Get current version"
        id: versions
        run: ./tracer/build.sh OutputCurrentVersionToGitHub